### PR TITLE
Add solidity tutorial

### PR DESCRIPTION
**Pull request by husseinrasti**
This page provides free education about smart contracts on open decentralized blockchains.

### CODE REVIEW

**Comment by monad-devrel** [comment]
Unfortunately this appears to be a paid resource for all but the very few first lessons.

**Comment by husseinrasti** [comment]
> Unfortunately this appears to be a paid resource for all but the very few first lessons.

Yes, you are right, because I learned solidity through this page before and it was a good source. But you can watch it for free on his YouTube channel.

https://www.youtube.com/@smartcontractprogrammer

**Comment by monad-devrel** [comment]
Oh ok, I'm happy to host the YouTube link instead of the site if you want to edit the PR to point to the YouTube link instead.

**Comment by husseinrasti** [comment]
for sure, I submitted

**Review by monad-devrel — APPROVED** [review]

**Pull request merged**
